spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    jdbc-url: jdbc:mysql://172.16.0.180:3306/register?characterEncoding=UTF-8&useSSL=true
    username: register
    password: register123

  activiti:
    database-schema-update: true
    check-process-definitions: false
    process-definition-location-prefix: classpath:/processes/